version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_USER: tu_usuario
      POSTGRES_PASSWORD: tu_password
      POSTGRES_DB: tu_base_de_datos
    volumes:
      - ./data_base:/var/lib/postgresql/data # carpeta donde se persistir치 la bd de postgres que levantes en local
      - ./init-scripts:/docker-entrypoint-initdb.d # carpeta donde se guardar치n los scripts de inicializaci칩n de la bd

    ports:
      - "5432:5432"
    restart: always

  app:
    build: ../
    container_name: futsalBackEnd
    ports:
      - "80:8082" # cambiar el puerto 80 por otro si ya est치 en uso
    restart: always
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/tu_base_de_datos # si tienes una local, cambiar esta url y las credenciales
      #SPRING_DATASOURCE_USERNAME: tu_usuario
      #SPRING_DATASOURCE_PASSWORD: tu_password

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: dev@dev.dev
      PGADMIN_DEFAULT_PASSWORD: dev
    ports:
      - "8085:80"    # puerto 8085 para acceder a pgadmin
    depends_on:
      - db