version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_USER: tu_usuario
      POSTGRES_PASSWORD: tu_password
      POSTGRES_DB: tu_base_de_datos
    volumes:
      - ./data_base:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d

    ports:
      - "5432:5432"
    restart: always

